### ISSUE TITLE
No applicable for office LTSC 2024

### ISSUE THREAD

**Issue by matolv** [mogeko/docker-vlmcsd#57]
Office LTSC 2024 was released in Sep 2024. The volume license could not be recoginized by KMS server correctly.

Here is official volume license:
https://learn.microsoft.com/en-us/office/volume-license-activation/gvlks

**Comment by mogeko** [comment]
Now, the `vlmccd.kmd` file contains the following products:

| No.  | Product Name                                         | No.  | Product Name                                   |
| ---- | ---------------------------------------------------- | ---- | ---------------------------------------------- |
| 1    | Windows Server 2025 Azure Core                       | 132  | Windows Server 2008 R2 Enterprise              |
| 2    | Windows Server 2025 Datacenter Azure Edition         | 133  | Windows Server 2008 R2 Datacenter              |
| 3    | Windows Server 2025 Datacenter                       | 134  | Windows Server 2008 R2 Enterprise for Itanium  |
| 4    | Windows Server 2025 Standard                         | 135  | Windows Server 2008 Web                        |
| 5    | Windows Server 2022 Azure Core                       | 136  | Windows Server 2008 Compute Cluster            |
| 6    | Windows Server 2022 Datacenter Azure Edition         | 137  | Windows Server 2008 Standard                   |
| 7    | Windows Server 2022 Datacenter                       | 138  | Windows Server 2008 Standard without Hyper-V   |
| 8    | Windows Server 2022 Standard                         | 139  | Windows Server 2008 Enterprise                 |
| 9    | Windows Server 2022 Datacenter (Semi-Annual Channel) | 140  | Windows Server 2008 Enterprise without Hyper-V |
| 10   | Windows Server 2022 Standard (Semi-Annual Channel)   | 141  | Windows Server 2008 Datacenter                 |
| 11   | Windows Server 2019 Azure Core                       | 142  | Windows Server 2008 Datacenter without Hyper-V |
| 12   | Windows Server 2019 Essentials                       | 143  | Windows Server 2008 Enterprise for Itanium     |
| 13   | Windows Server 2019 Datacenter                       | 144  | Office Access 2010                             |
| 14   | Windows Server 2019 Standard                         | 145  | Office Excel 2010                              |
| 15   | Windows Server 2019 ARM64                            | 146  | Office Groove 2010                             |
| 16   | Windows Server 2019 Datacenter (Semi-Annual Channel) | 147  | Office InfoPath 2010                           |
| 17   | Windows Server 2019 Standard (Semi-Annual Channel)   | 148  | Office Mondo 1 2010                            |
| 18   | Windows Server 2016 Azure Core                       | 149  | Office Mondo 2 2010                            |
| 19   | Windows Server 2016 Essentials                       | 150  | Office OneNote 2010                            |
| 20   | Windows Server 2016 Datacenter                       | 151  | Office OutLook 2010                            |
| 21   | Windows Server 2016 Standard                         | 152  | Office PowerPoint 2010                         |
| 22   | Windows Server 2016 ARM64                            | 153  | Office Professional Plus 2010                  |
| 23   | Windows Server 2016 Datacenter (Semi-Annual Channel) | 154  | Office Project Pro 2010                        |
| 24   | Windows Server 2016 Standard (Semi-Annual Channel)   | 155  | Office Project Standard 2010                   |
| 25   | Windows Server 2016 Cloud Storage                    | 156  | Office Publisher 2010                          |
| 26   | Windows 10/11 Enterprise multi-session               | 157  | Office Small Business Basics 2010              |
| 27   | Windows 10/11 Enterprise G                           | 158  | Office Standard 2010                           |
| 28   | Windows 10/11 Enterprise G N                         | 159  | Office Visio Premium 2010                      |
| 29   | Windows 10/11 Enterprise LTSC 2019-2021-2024         | 160  | Office Visio Pro 2010                          |
| 30   | Windows 10/11 Enterprise LTSC 2019-2021-2024 N       | 161  | Office Visio Standard 2010                     |
| 31   | Windows 10 Enterprise 2016 LTSB                      | 162  | Office Word 2010                               |
| 32   | Windows 10 Enterprise 2016 LTSB N                    | 163  | Office Access 2013                             |
| 33   | Windows 10 Enterprise 2015 LTSB                      | 164  | Office Excel 2013                              |
| 34   | Windows 10 Enterprise 2015 LTSB N                    | 165  | Office InfoPath 2013                           |
| 35   | Windows 10/11 Education                              | 166  | Office Lync 2013                               |
| 36   | Windows 10/11 Education N                            | 167  | Office Mondo 2013                              |
| 37   | Windows 10/11 Enterprise                             | 168  | Office OneNote 2013                            |
| 38   | Windows 10/11 Enterprise N                           | 169  | Office OutLook 2013                            |
| 39   | Windows 10/11 Pro                                    | 170  | Office PowerPoint 2013                         |
| 40   | Windows 10/11 Pro N                                  | 171  | Office Professional Plus 2013                  |
| 41   | Windows 10/11 Pro Education                          | 172  | Office Project Pro 2013                        |
| 42   | Windows 10/11 Pro Education N                        | 173  | Office Project Standard 2013                   |
| 43   | Windows 10/11 Pro Workstation                        | 174  | Office Publisher 2013                          |
| 44   | Windows 10/11 Pro Workstation N                      | 175  | Office Standard 2013                           |
| 45   | Windows 10/11 IoT Enterprise LTSC 2021-2024          | 176  | Office Visio Pro 2013                          |
| 46   | Windows 11 SE                                        | 177  | Office Visio Standard 2013                     |
| 47   | Windows 11 SE N                                      | 178  | Office Word 2013                               |
| 48   | Windows 10 S (Lean)                                  | 179  | Office Access 2013 (Pre-Release)               |
| 49   | Windows 10 Remote Server                             | 180  | Office Excel 2013 (Pre-Release)                |
| 50   | Windows 10/11 Preview Education                      | 181  | Office Groove 2013 (Pre-Release)               |
| 51   | Windows 10/11 Preview EducationN                     | 182  | Office InfoPath 2013 (Pre-Release)             |
| 52   | Windows 10/11 Preview Enterprise                     | 183  | Office Lync 2013 (Pre-Release)                 |
| 53   | Windows 10/11 Preview EnterpriseN                    | 184  | Office Mondo 2013 (Pre-Release)                |
| 54   | Windows 10/11 Preview EnterpriseS                    | 185  | Office OneNote 2013 (Pre-Release)              |
| 55   | Windows 10/11 Preview EnterpriseSN                   | 186  | Office Outlook 2013 (Pre-Release)              |
| 56   | Windows 10/11 Preview Professional                   | 187  | Office PowerPoint 2013 (Pre-Release)           |
| 57   | Windows 10/11 Preview ProfessionalN                  | 188  | Office Professional Plus 2013 (Pre-Release)    |
| 58   | Windows 10/11 Home                                   | 189  | Office Project Pro 2013 (Pre-Release)          |
| 59   | Windows 10/11 Home N                                 | 190  | Office Project Standard 2013 (Pre-Release)     |
| 60   | Windows 10/11 Home Country Specific                  | 191  | Office Publisher 2013 (Pre-Release)            |
| 61   | Windows 10/11 Home Single Language                   | 192  | Office Visio Pro 2013 (Pre-Release)            |
| 62   | Windows 10/11 Preview Core                           | 193  | Office Visio Standard 2013 (Pre-Release)       |
| 63   | Windows 10/11 Preview CoreN                          | 194  | Office Word 2013 (Pre-Release)                 |
| 64   | Windows 10/11 Preview CoreCountrySpecific            | 195  | Office Access 2016                             |
| 65   | Windows 10/11 Preview CoreSingleLanguage             | 196  | Office Excel 2016                              |
| 66   | Windows Preview Enterprise                           | 197  | Office Mondo 2016                              |
| 67   | Windows Preview Professional                         | 198  | Office Mondo R 2016                            |
| 68   | Windows Preview ProfessionalWMC                      | 199  | Office OneNote 2016                            |
| 69   | Windows Preview Core                                 | 200  | Office Outlook 2016                            |
| 70   | Windows Preview CoreARM                              | 201  | Office Powerpoint 2016                         |
| 71   | Windows Server Preview Datacenter                    | 202  | Office Professional Plus 2016                  |
| 72   | Windows Server Preview Standard                      | 203  | Office Project Pro 2016                        |
| 73   | Windows Server Preview Web                           | 204  | Office Project Pro 2016 C2R                    |
| 74   | Windows 8.1 Enterprise                               | 205  | Office Project Standard 2016                   |
| 75   | Windows 8.1 Enterprise N                             | 206  | Office Project Standard 2016 C2R               |
| 76   | Windows 8.1 Professional                             | 207  | Office Publisher 2016                          |
| 77   | Windows 8.1 Professional N                           | 208  | Office Skype for Business 2016                 |
| 78   | Windows 8.1 Embedded Industry Automotive             | 209  | Office Standard 2016                           |
| 79   | Windows 8.1 Embedded Industry Enterprise             | 210  | Office Visio Pro 2016                          |
| 80   | Windows 8.1 Embedded Industry Professional           | 211  | Office Visio Pro 2016 C2R                      |
| 81   | Windows 8.1 Core Connected                           | 212  | Office Visio Standard 2016                     |
| 82   | Windows 8.1 Core Connected N                         | 213  | Office Visio Standard 2016 C2R                 |
| 83   | Windows 8.1 Core Connected Country Specific          | 214  | Office Word 2016                               |
| 84   | Windows 8.1 Core Connected Single Language           | 215  | Office Professional Plus 2019 Preview          |
| 85   | Windows 8.1 Core                                     | 216  | Office Project Pro 2019 Preview                |
| 86   | Windows 8.1 Core N                                   | 217  | Office Visio Pro 2019 Preview                  |
| 87   | Windows 8.1 Core Country Specific                    | 218  | Office Access 2019                             |
| 88   | Windows 8.1 Core Single Language                     | 219  | Office Excel 2019                              |
| 89   | Windows 8.1 Core ARM                                 | 220  | Office Outlook 2019                            |
| 90   | Windows 8.1 Professional WMC                         | 221  | Office Powerpoint 2019                         |
| 91   | Windows 8.1 Professional Student                     | 222  | Office Professional Plus 2019                  |
| 92   | Windows 8.1 Professional Student N                   | 223  | Office Project Pro 2019                        |
| 93   | Windows 8 Enterprise                                 | 224  | Office Project Standard 2019                   |
| 94   | Windows 8 Enterprise N                               | 225  | Office Publisher 2019                          |
| 95   | Windows 8 Professional                               | 226  | Office Skype for Business 2019                 |
| 96   | Windows 8 Professional N                             | 227  | Office Standard 2019                           |
| 97   | Windows 8 Embedded Industry Enterprise               | 228  | Office Visio Pro 2019                          |
| 98   | Windows 8 Embedded Industry Professional             | 229  | Office Visio Standard 2019                     |
| 99   | Windows 8 Embedded POSReady [Beta]                   | 230  | Office Word 2019                               |
| 100  | Windows 8 Core                                       | 231  | Office Professional Plus 2021 Preview          |
| 101  | Windows 8 Core N                                     | 232  | Office Project Pro 2021 Preview                |
| 102  | Windows 8 Core Country Specific                      | 233  | Office Visio Pro 2021 Preview                  |
| 103  | Windows 8 Core Single Language                       | 234  | Office Access LTSC 2021                        |
| 104  | Windows 8 Core ARM                                   | 235  | Office Excel LTSC 2021                         |
| 105  | Windows 8 Professional WMC                           | 236  | Office Outlook LTSC 2021                       |
| 106  | Windows 7 Enterprise                                 | 237  | Office Powerpoint LTSC 2021                    |
| 107  | Windows 7 Enterprise E                               | 238  | Office LTSC Professional Plus 2021             |
| 108  | Windows 7 Enterprise N                               | 239  | Office Project Pro 2021                        |
| 109  | Windows 7 Professional                               | 240  | Office Project Standard 2021                   |
| 110  | Windows 7 Professional E                             | 241  | Office Publisher LTSC 2021                     |
| 111  | Windows 7 Professional N                             | 242  | Office Skype for Business LTSC 2021            |
| 112  | Windows 7 ThinPC                                     | 243  | Office LTSC Standard 2021                      |
| 113  | Windows 7 Embedded POSReady                          | 244  | Office Visio LTSC Pro 2021                     |
| 114  | Windows 7 Embedded Standard                          | 245  | Office Visio LTSC Standard 2021                |
| 115  | Windows Vista Business                               | 246  | Office Word LTSC 2021                          |
| 116  | Windows Vista Business N                             | 247  | Office Professional Plus 2024 Preview          |
| 117  | Windows Vista Enterprise                             | 248  | Office Project Pro 2024 Preview                |
| 118  | Windows Vista Enterprise N                           | 249  | Office Visio Pro 2024 Preview                  |
| 119  | Windows Server 2012 R2 Essentials                    | 250  | Office Access LTSC 2024                        |
| 120  | Windows Server 2012 R2 Datacenter                    | 251  | Office Excel LTSC 2024                         |
| 121  | Windows Server 2012 R2 Standard                      | 252  | Office Outlook LTSC 2024                       |
| 122  | Windows Server 2012 R2 Cloud Storage                 | 253  | Office Powerpoint LTSC 2024                    |
| 123  | Windows Server 2012 Essentials                       | 254  | Office LTSC Professional Plus 2024             |
| 124  | Windows Server 2012 Datacenter                       | 255  | Office Project Pro 2024                        |
| 125  | Windows Server 2012 Standard                         | 256  | Office Project Standard 2024                   |
| 126  | Windows Server 2012 MultiPoint Premium               | 257  | Office Skype for Business LTSC 2024            |
| 127  | Windows Server 2012 MultiPoint Standard              | 258  | Office LTSC Standard 2024                      |
| 128  | Windows MultiPoint Server 2010                       | 259  | Office Visio LTSC Pro 2024                     |
| 129  | Windows Server 2008 R2 Web                           | 260  | Office Visio LTSC Standard 2024                |
| 130  | Windows Server 2008 R2 HPC Edition                   | 261  | Office Word LTSC 2024                          |
| 131  | Windows Server 2008 R2 Standard                      |      |                                                |
